version: "3.7"
services:
  webapi:
    restart: always
    container_name: webapi_1
    image: registry.cn-hangzhou.aliyuncs.com/jerryan999/youzan_captcha:v2
    ports:
      - 5004:5000


  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx_1
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    ports:
      - 8001:80
    # depends_on:
    #   - webapi
